CREATE DATABASE DB_FIRECONVERTER
GO
USE DB_FIRECONVERTER

CREATE TABLE USUARIO(
COD_USER INT IDENTITY(1,1),
NOME VARCHAR (50) NOT NULL,
EMAIL VARCHAR (50) NOT NULL,
SENHA VARCHAR (50) NOT NULL
PRIMARY KEY (COD_USER))

CREATE TABLE FORMATO_AUDIO(
COD_FORM INT IDENTITY (1,1) NOT NULL,
EXTENSAO VARCHAR (10) NOT NULL,
DESCRICAO VARCHAR (200) NOT NULL
PRIMARY KEY (COD_FORM)
)

CREATE TABLE FORMATO_VIDEO(
COD_FORM INT IDENTITY (1,1) NOT NULL,
EXTENSAO VARCHAR (10) NOT NULL,
DESCRICAO VARCHAR (200) NOT NULL
PRIMARY KEY (COD_FORM)
)

CREATE TABLE ERRO(
COD_ERRO INT IDENTITY(1,1) NOT NULL,
CATEGORIA VARCHAR(200) NOT NULL,
DESCRICAO VARCHAR(200)
PRIMARY KEY(COD_ERRO))



CREATE TABLE AUDIO
(COD_A INT IDENTITY(1,1) NOT NULL,
 ENDERECO VARCHAR(200) NOT NULL,
 EXTENSAO VARCHAR (10) NOT NULL
 PRIMARY KEY (COD_A)
 )

 CREATE TABLE VIDEO
(COD_VIDEO INT IDENTITY(1,1) NOT NULL,
 ENDERECO VARCHAR(200) NOT NULL,
 EXTENSAO VARCHAR (10) NOT NULL
 PRIMARY KEY (COD_VIDEO)
 )


 